language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3
install:
  - pip install coveralls
script:
  - python -m test_wrecord
  - coverage run --source=wrecord setup.py test
after_success: coveralls